import React, { useState, useEffect, useMemo } from 'react'

const LOCATIONS = [
  {id:'boston', title:'Boston / Cape Cod', sub:'EASY GATHER', icon:'🏡', price:'$$', bullets:['Drive for many','Lots of house options','Works for all ages']},
  {id:'jamaica', title:'Jamaica', sub:'HOMECOMING', icon:'🇯🇲', price:'$$$', bullets:['Most meaningful','Big Jamaican community','Warm big houses'], featured:true},
  {id:'florida', title:'Florida', sub:'MIDDLE GROUND', icon:'🌴', price:'$$', bullets:['Big Jamaican community','Warm big houses','Works for both sides']},
  {id:'newyork', title:'New York', sub:'CITY & FAMILY HUB', icon:'🗽', price:'$$', bullets:['Big Jamaican community in NYC area','Easy Amtrak/bus from Boston','Upstate houses for big groups','Works for both sides']},
  {id:'other', title:'Other - Custom Idea', sub:'YOUR IDEA', icon:'💡', price:'', bullets:['Have another idea?','Suggest a place'], isOther:true},
]
const WHEN = [
  {id:'earlyFall', title:'Early Fall', date:'Sept-Oct 2027', note:'Best balance - Recommended for Late 2027/28', rec:true},
  {id:'winter', title:'Winter Dry Season', date:'Nov 2027 - Apr 2028', note:'Best for Jamaica / FL'},
  {id:'lateSpring', title:'Late Spring', date:'May-June 2028', note:'Best NE weather'},
]
const LOVED = [{id:'tristan',name:'Tristan'},{id:'mom',name:'Mom'},{id:'dad',name:'Dad'},{id:'vassell',name:'Vassell'},{id:'danny',name:'Danny'}]

function useLS(key, init){
  const [v,setV]=useState(()=>{try{const s=localStorage.getItem(key);return s?JSON.parse(s):init}catch{return init}})
  useEffect(()=>{localStorage.setItem(key,JSON.stringify(v))},[key,v])
  return [v,setV]
}

export default function App(){
  const [locVotes,setLocVotes]=useLS('memorial_location_votes_v2',{})
  const [whenVotes,setWhenVotes]=useLS('memorial_when_votes_v2',{})
  const [otherIdea,setOtherIdea]=useLS('memorial_other_idea','')
  const [otherVotes,setOtherVotes]=useLS('memorial_other_votes',0)
  const [headcount,setHeadcount]=useLS('memorial_headcount_attending',[])
  const [chat,setChat]=useLS('memorial_public_chat',[{id:'1',name:'Shawn',location:'Boston area',message:'Attending with 2 - excited to honor Mom & Dad',time:Date.now()-86400000}])
  const [photos,setPhotos]=useLS('memorial_loved_photos',{})
  const [name,setName]=useState('')
  const [from,setFrom]=useState('Boston area')
  const [status,setStatus]=useState('Yes - Attending')
  const [adults,setAdults]=useState(1)
  const [kids,setKids]=useState(0)
  const [note,setNote]=useState('')
  const [chatName,setChatName]=useState('')
  const [chatLoc,setChatLoc]=useState('Boston area')
  const [chatMsg,setChatMsg]=useState('')
  const total=Number(adults)+Number(kids)
  const daysLeft=useMemo(()=>{const d=new Date('2026-12-04T23:59:59')-new Date();return Math.max(0,Math.ceil(d/86400000))},[])
  const totalLoc=Object.values(locVotes).reduce((a,b)=>a+(b||0),0)+otherVotes
  const totalWhen=Object.values(whenVotes).reduce((a,b)=>a+(b||0),0)
  const eligible=headcount.filter(h=>h.children>=2 && (h.status.includes('Yes')||h.status.includes('Maybe'))).length
  const totalPeople=headcount.filter(h=>h.status.includes('Yes')).reduce((s,h)=>s+(h.total||0),0)
  function voteLoc(id){setLocVotes(v=>({...v,[id]:(v[id]||0)+1}))}
  function voteWhen(id){setWhenVotes(v=>({...v,[id]:(v[id]||0)+1}))}
  function addHead(e){e.preventDefault();if(!name)return alert('Add name');setHeadcount([{id:Date.now().toString(),name,location:from,status,adults:Number(adults),children:Number(kids),total,message:note,time:Date.now()},...headcount]);setName('');setNote('')}
  function addChat(e){e.preventDefault();if(!chatName||!chatMsg)return alert('Name+message');setChat([{id:Date.now().toString(),name:chatName,location:chatLoc,message:chatMsg,time:Date.now()},...chat]);setChatMsg('')}
  function uploadPhoto(id,f){if(!f)return;const r=new FileReader();r.onload=ev=>setPhotos(p=>({...p,[id]:ev.target.result}));r.readAsDataURL(f)}
  function exportData(){const data={locVotes,whenVotes,otherIdea,otherVotes,headcount,chat,photos,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`paul-family-late-2027-28-${new Date().toISOString().slice(0,10)}.json`;a.click()}
  return(
    <div className="min-h-screen bg-[#fdf8f0] text-[#1a3d2e]">
      <div className="sticky top-0 z-50 bg-[#fdf8f0]/90 backdrop-blur border-b border-[#e8dcc8]"><div className="max-w-5xl mx-auto px-4 py-3 flex justify-between items-center"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-[#1a3d2e] text-white grid place-items-center">🌿</div><span className="serif font-bold">Paul Family • Late 2027/28</span><span className="ml-2 text-[10px] px-2 py-1 rounded-full bg-green-100 text-green-800">● Live Preview</span></div></div></div>
      <div className="max-w-5xl mx-auto px-4 py-6 space-y-6">
        <div className="rounded-[24px] bg-[#1a3d2e] text-white p-6 md:p-8"><div className="inline-flex bg-[#c9a86a] text-[#1a3d2e] px-3 py-1 rounded-full text-[11px] font-bold tracking-widest">CURRENT FOCUS</div><h1 className="serif text-2xl md:text-3xl mt-4 font-bold">CURRENT FOCUS: Where + Loved Ones — Late 2027/28 Gathering</h1><p className="mt-3 text-white/80">We are focusing on ONE thing at a time so it doesn't take months of group texts. We are focused on <b className="text-white">gathering ALL information by Dec 4, 2026</b> — This deadline is to gather votes, headcount, and photos, NOT for the trip itself. Trip is <b className="text-[#c9a86a]">Late 2027/28 (Sept 2027 - Apr 2028)</b>.</p><div className="mt-6 bg-white/10 rounded-2xl p-4 border border-white/10 text-center"><div className="text-[11px] tracking-widest text-[#c9a86a]">INFO GATHERING DEADLINE</div><div className="serif text-5xl font-bold mt-2">{daysLeft}</div><div className="text-white/70 text-sm">days left until Dec 4, 2026</div></div></div>
        <div className="rounded-[20px] bg-[#fff8e7] border border-[#e8dcc8] p-5"><span className="px-3 py-1 rounded-full bg-[#1a3d2e] text-white text-[11px] font-bold">GOAL: GATHER ALL INFORMATION BY DEC 4TH — LOCATION AND DATE</span><p className="text-sm mt-3 text-[#5a4a3a]">Only {daysLeft} days left to gather all location votes, date votes, headcount, and photos — Trip itself is Late 2027/28. Agree on location and date by Dec 4th. LIVE: {totalLoc} location votes • {totalWhen} date votes</p></div>
        <div className="rounded-[20px] bg-white border p-6"><h3 className="serif font-bold">Who's Invited</h3><p className="mt-2 text-[#5a4a3a]">Everyone — Boston, other MA, other U.S. states, Jamaica, and beyond. If you can't travel, we'll have a virtual option so you're still part of it.</p></div>
        <div id="vote" className="rounded-[24px] bg-white border p-6 md:p-8"><h2 className="serif text-2xl font-bold">📍 Vote — Where?</h2><p className="text-sm text-[#6b5d4d]">Tap to vote — saved on this device.</p><div className="grid md:grid-cols-2 gap-4 mt-5">{LOCATIONS.map(l=>{const votes=l.id==='other'?otherVotes:(locVotes[l.id]||0);const pct=totalLoc?Math.round(votes/totalLoc*100):0;return(<div key={l.id} className={`rounded-2xl border p-5 ${l.featured?'border-[#c9a86a] bg-[#fff8e7]':'bg-[#fdf8f0]'}`}><div className="flex justify-between"><b>{l.icon} {l.title}</b><span className="text-[11px] px-2 py-1 rounded-full bg-white border">{l.sub} {l.price}</span></div><ul className="mt-3 text-sm text-[#5a4a3a]">{l.bullets.map(b=><li key={b}>• {b}</li>)}</ul>{l.isOther&&<input value={otherIdea} onChange={e=>setOtherIdea(e.target.value)} placeholder="Type your idea here - e.g., Atlanta, Toronto..." className="mt-3 w-full border rounded-xl px-3 py-2 text-sm"/>}<div className="mt-3 h-2 bg-[#e8dcc8] rounded-full overflow-hidden"><div className="h-full bg-[#1a3d2e]" style={{width:`${pct}%`}}></div></div><div className="flex justify-between text-xs mt-1"><span>{votes} votes</span><span>{pct}%</span></div><button onClick={()=>l.isOther?setOtherVotes(v=>v+1):voteLoc(l.id)} className="mt-3 w-full bg-[#1a3d2e] text-white rounded-xl py-2 text-sm">Vote for {l.title}</button></div>)})}</div></div>
        <div id="when" className="rounded-[24px] bg-white border p-6 md:p-8"><h2 className="serif text-2xl font-bold">When works for you? — Late 2027/28</h2><div className="grid md:grid-cols-3 gap-4 mt-4">{WHEN.map(w=>{const v=whenVotes[w.id]||0;const pct=totalWhen?Math.round(v/totalWhen*100):0;return(<div key={w.id} className={`rounded-2xl border p-5 ${w.rec?'bg-[#fff8e7] border-[#c9a86a]':'bg-[#fdf8f0]'}`}><b>{w.title} {w.rec&&<span className="text-[10px] ml-2 px-2 py-0.5 rounded-full bg-[#c9a86a]">Recommended</span>}</b><div className="text-sm font-semibold">{w.date}</div><div className="text-xs text-[#6b5d4d]">{w.note}</div><div className="mt-3 h-2 bg-[#e8dcc8] rounded-full overflow-hidden"><div className="h-full bg-[#1a3d2e]" style={{width:`${pct}%`}}></div></div><div className="flex justify-between text-xs mt-1"><span>{v} votes</span><span>{pct}%</span></div><button onClick={()=>voteWhen(w.id)} className="mt-3 w-full bg-white border border-[#1a3d2e] rounded-xl py-2 text-sm">Vote for {w.title}</button></div>)})}</div></div>
        <div id="loved" className="rounded-[24px] bg-white border p-6 md:p-8"><h2 className="serif text-2xl font-bold">❤️ Our Loved Ones</h2><p className="text-sm text-[#6b5d4d]">Our loved ones we gather to honor first - 5 cards: Tristan, Mom, Dad, Vassell, Danny</p><div className="grid grid-cols-2 md:grid-cols-5 gap-4 mt-5">{LOVED.map(p=>{const ph=photos[p.id];return(<div key={p.id} className="rounded-2xl border bg-[#fdf8f0] p-3 text-center"><div className="w-full aspect-square rounded-xl bg-[#e8dcc8] overflow-hidden grid place-items-center">{ph?<img src={ph} className="w-full h-full object-cover"/>:<span className="text-3xl">🕊️</span>}</div><div className="font-semibold mt-2">{p.name}</div><label className="mt-2 block text-[11px] px-2 py-1 rounded-full bg-white border cursor-pointer">Add photo<input type="file" accept="image/*" className="hidden" onChange={e=>uploadPhoto(p.id,e.target.files[0])}/></label></div>)})}</div></div>
        <div id="head" className="rounded-[24px] bg-white border p-6 md:p-8"><h2 className="serif text-2xl font-bold">Who's Coming — Live Head Count</h2><div className="grid grid-cols-3 gap-3 mt-4"><div className="rounded-xl bg-[#1a3d2e] text-white p-3"><div className="text-[11px] opacity-70">Families</div><div className="text-2xl font-bold">{headcount.filter(h=>h.status.includes('Yes')).length}</div></div><div className="rounded-xl bg-[#fff8e7] border p-3"><div className="text-[11px]">Total People</div><div className="text-2xl font-bold">{totalPeople}</div></div><div className="rounded-xl bg-[#f5efe2] border p-3"><div className="text-[11px]">2+ kids (Fund)</div><div className="text-2xl font-bold">{eligible}</div></div></div><form onSubmit={addHead} className="mt-6 grid md:grid-cols-2 gap-3 bg-[#fdf8f0] border rounded-2xl p-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your Name" className="border rounded-xl px-3 py-2"/><select value={from} onChange={e=>setFrom(e.target.value)} className="border rounded-xl px-3 py-2"><option>Boston area</option><option>Other MA</option><option>Other US</option><option>Jamaica</option><option>Other</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-xl px-3 py-2"><option>Yes - Attending</option><option>Maybe</option><option>Can't make it but want virtual</option></select><div className="flex gap-2"><label className="flex-1 text-xs">Adults<input type="number" min="0" value={adults} onChange={e=>setAdults(e.target.value)} className="w-full border rounded-xl px-2 py-1"/></label><label className="flex-1 text-xs">Kids<input type="number" min="0" value={kids} onChange={e=>setKids(e.target.value)} className="w-full border rounded-xl px-2 py-1"/></label></div><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Notes" className="md:col-span-2 border rounded-xl px-3 py-2"/><div className="md:col-span-2 flex justify-between items-center"><span className="text-sm font-semibold">Total: {total} {kids>=2&&<span className="ml-2 text-[10px] px-2 py-0.5 rounded-full bg-[#c9a86a]">Eligible for Support Fund</span>}</span><button className="bg-[#1a3d2e] text-white px-5 py-2 rounded-xl text-sm">Add Head Count - Attending with {total}</button></div></form><div className="mt-5 space-y-2">{headcount.map(h=><div key={h.id} className="flex justify-between border rounded-xl p-3 bg-[#fdf8f0]"><div><b>{h.name}</b> <span className="text-xs border px-2 py-0.5 rounded-full bg-white ml-2">{h.location}</span><div className="text-sm">Attending with {h.total} ({h.adults} adults, {h.children} kids) {h.children>=2&&<span className="ml-2 text-[10px] px-2 py-0.5 rounded-full bg-[#c9a86a]">Fund eligible</span>}</div></div><button onClick={()=>setHeadcount(headcount.filter(x=>x.id!==h.id))} className="text-xs text-red-600">Remove</button></div>)}</div></div>
        <div id="chat" className="rounded-[24px] bg-white border p-6 md:p-8"><h2 className="serif text-2xl font-bold">Public Chat — For Those Attending</h2><form onSubmit={addChat} className="mt-4 grid md:grid-cols-3 gap-3 bg-[#fdf8f0] border rounded-2xl p-4"><input value={chatName} onChange={e=>setChatName(e.target.value)} placeholder="Your Name" className="border rounded-xl px-3 py-2"/><input value={chatLoc} onChange={e=>setChatLoc(e.target.value)} placeholder="Boston area" className="border rounded-xl px-3 py-2"/><div className="md:col-span-3 flex gap-2"><input value={chatMsg} onChange={e=>setChatMsg(e.target.value)} placeholder="I'm attending with 3..." className="flex-1 border rounded-xl px-3 py-2"/><button className="bg-[#1a3d2e] text-white px-5 rounded-xl text-sm">Post</button></div></form><div className="mt-5 space-y-3">{chat.map(m=><div key={m.id} className="border rounded-xl p-3 bg-[#fdf8f0] flex gap-3"><div className="w-8 h-8 rounded-full bg-[#1a3d2e] text-white grid place-items-center text-sm">{m.name[0]}</div><div><div className="text-sm font-semibold">{m.name} <span className="text-xs font-normal text-[#6b5d4d]">{m.location}</span></div><div className="text-sm">{m.message}</div></div></div>)}</div></div>
        <div className="flex gap-3"><button onClick={exportData} className="bg-white border px-4 py-2 rounded-xl text-sm">Export All Data (JSON)</button></div>
      </div>
    </div>
  )
}
